# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170928_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(help_text='Enter subcategory name', max_length=200),
        ),
    ]
