# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_dish_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='choises',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2, null=True),
        ),
    ]
