# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_choises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='choises',
        ),
    ]
