# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_category_choises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Restaurant name', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='worker name', max_length=30)),
                ('patromymic', models.CharField(help_text='worker patronymic', max_length=30, null=True)),
                ('surname', models.CharField(help_text='worker surname', max_length=30)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Restaurant')),
            ],
        ),
    ]
