# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_restaurant_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(help_text='City', max_length=20, null=True),
        ),
    ]
